language: python
python:
  - "2.7"

install:
  - pip install sphinx
  
script:
  - cd workspace
  - make html
  
branches:
  only:
  - master
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
